---
title: "Project"
author: "David Tessier"
date: "11/09/2021"
output: html_document
---

```{r}
install.packages("tidyverse", type = "binary")
install.packages("ggrepel", type = "binary")
install.packages("ggimage", type = "binary")
install.packages("nflfastR", type = "binary")
install.packages("gsisdecoder")

library(tidyverse, warn.conflicts = FALSE)
library(ggrepel, warn.conflicts = FALSE)
library(ggimage, warn.conflicts = FALSE)
library(nflfastR, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(nflreadr, warn.conflicts = FALSE)
library(nflscrapR, warn.conflicts = FALSE)

# makes R prefer not to display numbers in scientific notation
options(scipen = 9999)
```

```{r}
# Loading all regular season games from 2015 - 2020
data1 <- load_pbp(2015:2020) %>% 
  filter(season_type == "REG")

team_abbr <- c("ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE",  "DAL", "DEN", "DET", "GB", "HOU", "IND", "JAX", "KC", "LA", "LAC", "LV", "MIA", "MIN", "NE", "NYG", "NYJ", "NO", "PHI", "PIT", "TEN", "SEA", "SF", "TB", "WAS")
```

### Evaluate drives that began with a QB drop-back 
```{r}
# Drives that began with a QB drop-back on first down with win probability 
# between 20 and 80, excluding the final 2 minutes of the half when everyone is
# pass-happy.

fd_dropbacks <- data1 %>%
  filter(down==1 & qb_dropback==1 & wp>= .20 & wp<= .80 & half_seconds_remaining>120 & !is.na(epa)) %>%
  group_by(posteam) %>%
  summarize(
    scoring_drive = mean(drive_ended_with_score), 
    epa = mean(epa),
    wpa = mean(wpa),
    success_rate = mean(success),
    yards_per_play = mean(yards_gained), 
    plays = n()
    ) %>% 
  ungroup() %>%
  left_join(teams_colors_logos , by = c('posteam' = 'team_abbr')) 

fd_dropbacks %>%
  ggplot(aes(x = plays, y = epa)) +
  #horizontal line with mean expected points added
  geom_hline(yintercept = mean(fd_dropbacks$epa),
             color = "red", linetype = "dashed", alpha=0.5) +
  #vertical line with mean win probability added
  geom_vline(xintercept =  mean(fd_dropbacks$plays),
             color = "red", linetype = "dashed", alpha=0.5) +
  #add points for the teams with the right colors
  #cex controls point size and alpha the transparency (alpha = 1 is normal)
  geom_point(color = fd_dropbacks$team_color, cex=fd_dropbacks$plays / 150, alpha = .6) +
  #add names using ggrepel, which tries to make them not overlap
  geom_text_repel(aes(label=posteam)) +
  stat_smooth(geom = 'line', alpha = 0.5, se = FALSE, method = 'lm') +
  labs(x = "# of QB Dropbacks on 1st Down's", 
       y = "Expected Points Added per Play",
       title = "EPA for QB Dropbacks on 1st Down, 2015-2020",
       caption = "Data: @nflfastR") +
  theme_bw() +
  theme(plot.title = element_text(size = 14, hjust = 0.5, face = "bold")) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))
  
```